"""
CORTEX — Cross-Pollination Report Generator
Connects insights across different research fields.
"""

from datetime import datetime
from core.utils import write_file


def generate_cross_pollination(ai_engine, persona_prompt, memory):
    """
    Generate a cross-pollination report connecting two different research fields.

    Returns a dict with the report content and metadata.
    """

    # Get recent topics to find interesting connections
    recent_entries = memory.history.get("entries", [])[-7:]
    recent_topics = list(set(e.get("topic", "") for e in recent_entries))

    if len(recent_topics) < 2:
        recent_topics = ["NLP", "BCI"]  # Default pair

    prompt = f"""You are generating a "Cross-Pollination Report" — finding unexpected
connections between different AI research fields.

Recent fields covered: {', '.join(recent_topics)}

Pick TWO fields from the list and find a GENUINE, technically sound connection.
This should be a real, actionable research hypothesis — not a vague analogy.

Provide:
1. "field_a": First field name
2. "field_b": Second field name
3. "title": A compelling title for the connection (e.g., "Diffusion Denoising for EEG Signals")
4. "hypothesis": A 2-3 sentence research hypothesis
5. "mechanism": How the technique from field_a could specifically apply to field_b
6. "mermaid_diagram": A Mermaid.js flowchart showing the connection (use graph TD syntax)
7. "feasibility": One of ["Highly Feasible", "Promising", "Speculative", "Long-shot"]
8. "existing_work": Any existing papers or projects that hint at this connection
9. "keywords": 3-5 keywords

Respond as a JSON object."""

    result = ai_engine.generate(
        prompt=prompt,
        system_prompt=persona_prompt,
        json_mode=True,
        use_search=True,
    )

    if not result or not isinstance(result, dict):
        return None

    # Generate the report markdown
    date = datetime.now().strftime("%Y-%m-%d")
    date_slug = datetime.now().strftime("%Y_%m_%d")
    filename = f"blogs/cross_pollination_{date_slug}.md"

    title = result.get("title", "Cross-Field Connection")
    field_a = result.get("field_a", "Field A")
    field_b = result.get("field_b", "Field B")

    content = f"""# 🔗 Cross-Pollination Report: {title}

**Date:** {date}
**Fields:** {field_a} ↔ {field_b}
**Feasibility:** {result.get('feasibility', 'Unknown')}

---

## Hypothesis

{result.get('hypothesis', 'No hypothesis generated.')}

## Mechanism

{result.get('mechanism', 'No mechanism described.')}

## Connection Map

```mermaid
{result.get('mermaid_diagram', 'graph TD\\n  A[Field A] --> B[Field B]')}
```

## Existing Work

{result.get('existing_work', 'No existing work found.')}

---

*Generated by CORTEX — Cross-Pollination Engine*
"""

    write_file(filename, content)
    print(f"  [CROSS-POLLINATION] Generated: {title}")

    return {
        "filename": filename,
        "title": title,
        "keywords": result.get("keywords", []),
    }
