"""
CORTEX — Paper Deep Dive Generator
Generates a detailed breakdown of the week's most impactful paper.
"""

from datetime import datetime
from core.utils import write_file, week_number, year


def generate_paper_deep_dive(ai_engine, persona_prompt, memory):
    """
    Generate a deep dive into the most impactful paper from the past week.

    Returns the filename of the generated deep dive.
    """

    # Gather arxiv IDs and keywords from recent entries
    recent_entries = memory.history.get("entries", [])[-7:]
    arxiv_ids = []
    all_keywords = []
    for entry in recent_entries:
        arxiv_ids.extend(entry.get("arxiv_ids", []))
        all_keywords.extend(entry.get("keywords", []))

    wk = week_number()
    yr = year()

    prompt = f"""Select the MOST impactful recent AI research paper from this week's coverage
and create a comprehensive deep dive.

Recent paper references: {', '.join(arxiv_ids[:10]) if arxiv_ids else 'None tracked'}
Key topics this week: {', '.join(set(all_keywords)[:20])}

If no specific papers were tracked, select a genuinely important recent paper
from NLP, CV, XAI, or BCI published in the last 7-14 days.

Provide a JSON object with:
1. "paper_title": Full title of the paper
2. "authors": Key authors (first 3)
3. "arxiv_id": ArXiv ID if available
4. "field": Which field this belongs to

5. "problem": What problem does this paper solve? (2-3 sentences)
6. "method": How does it solve it? Technical description (3-4 sentences)
7. "key_innovation": The single most novel contribution (1-2 sentences)

8. "mermaid_architecture": A Mermaid.js diagram of the proposed architecture/method
   (use graph TD or flowchart TD syntax, keep it clean and readable)

9. "code_snippet": A minimal PyTorch-style pseudocode (10-20 lines) showing
   the core idea as a Python class or function

10. "results": Key quantitative results (2-3 sentences)
11. "impact": Why this matters for the field (2-3 sentences)
12. "limitations": Honest limitations (1-2 sentences)
13. "keywords": 5 keywords"""

    result = ai_engine.generate(
        prompt=prompt,
        system_prompt=persona_prompt,
        json_mode=True,
        use_search=True,
    )

    filename = f"papers/week_{wk:02d}_{yr}.md"

    if not result or not isinstance(result, dict):
        content = f"# Paper Deep Dive — Week {wk}, {yr}\n\n*Analysis pending.*\n"
        write_file(filename, content)
        return filename

    content = f"""# 📄 Paper Deep Dive — Week {wk}, {yr}

## {result.get('paper_title', 'Untitled Paper')}

**Authors:** {result.get('authors', 'Unknown')}
**ArXiv:** {result.get('arxiv_id', 'N/A')}
**Field:** {result.get('field', 'AI/ML')}

---

## The Problem

{result.get('problem', 'Not described.')}

## The Method

{result.get('method', 'Not described.')}

### Key Innovation

> {result.get('key_innovation', 'Not identified.')}

## Architecture

```mermaid
{result.get('mermaid_architecture', 'graph TD\\n  A[Input] --> B[Model] --> C[Output]')}
```

## Core Implementation

```python
{result.get('code_snippet', '# Implementation pending')}
```

## Results

{result.get('results', 'No results reported.')}

## Impact

{result.get('impact', 'Impact assessment pending.')}

## Limitations

{result.get('limitations', 'No limitations noted.')}

---

*Deep dive generated by CORTEX — Paper Analysis Engine*
"""

    write_file(filename, content)
    print(f"  [PAPER] Deep dive: {result.get('paper_title', 'Unknown')[:60]}")

    return filename
