"""
CORTEX — Weekly Synthesis Blog Generator
Generates the Sunday synthesis report from the week's insights.
"""

from datetime import datetime
from core.utils import read_file, write_file, week_number, year


def generate_weekly_synthesis(ai_engine, persona_prompt, memory):
    """
    Generate a comprehensive weekly synthesis blog from the week's content.

    Returns the filename of the generated blog.
    """

    # Gather the week's entries from memory
    recent_entries = memory.history.get("entries", [])[-7:]

    # Build context from the week
    week_context = ""
    all_keywords = []
    for entry in recent_entries:
        date = entry.get("date", "unknown")
        topic = entry.get("topic", "unknown")
        keywords = entry.get("keywords", [])
        messages = entry.get("commit_messages", [])
        all_keywords.extend(keywords)

        week_context += f"\n[{date}] {topic}:\n"
        for msg in messages[:5]:
            week_context += f"  - {msg}\n"

    wk = week_number()
    yr = year()

    prompt = f"""Generate a comprehensive Weekly Synthesis Report for Week {wk} of {yr}.

Here is a summary of this week's research coverage:
{week_context[:4000]}

Key terms this week: {', '.join(set(all_keywords)[:30])}

Create a structured blog post with:
1. "title": An engaging title for the week (e.g., "Week 18: The Attention Wars Intensify")
2. "executive_summary": 2-3 sentences summarizing the week's biggest theme
3. "top_breakthrough": The single most important finding of the week (3-4 sentences)
4. "field_highlights": A brief highlight for each field covered this week
5. "connections": Any cross-field patterns or trends observed
6. "outlook": 1-2 sentences on what to watch for next week
7. "mermaid_diagram": A Mermaid.js diagram showing the week's key connections
8. "paper_of_the_week": Title and brief description of the most impactful paper

Respond as a JSON object."""

    result = ai_engine.generate(
        prompt=prompt,
        system_prompt=persona_prompt,
        json_mode=True,
        use_search=True,
    )

    filename = f"blogs/week_{wk:02d}_{yr}.md"

    if not result or not isinstance(result, dict):
        # Fallback
        content = f"# Weekly Synthesis — Week {wk}, {yr}\n\n*Report generation pending.*\n"
        write_file(filename, content)
        return filename

    title = result.get("title", f"Week {wk} Synthesis")

    content = f"""# 📡 {title}

**Week {wk}, {yr}** | Generated by CORTEX

---

## Executive Summary

{result.get('executive_summary', 'No summary available.')}

## 🏆 Top Breakthrough

{result.get('top_breakthrough', 'No breakthrough identified.')}

## Field Highlights

{_format_highlights(result.get('field_highlights', {}))}

## 🔗 Cross-Field Connections

{result.get('connections', 'No cross-field patterns detected.')}

## Connection Map

```mermaid
{result.get('mermaid_diagram', 'graph TD\\n  A[Week Start] --> B[Week End]')}
```

## 📄 Paper of the Week

{result.get('paper_of_the_week', 'No paper selected.')}

## 🔮 Outlook

{result.get('outlook', 'Continue monitoring all sectors.')}

---

*This report was autonomously generated by CORTEX — an AI research entity.*
"""

    write_file(filename, content)
    print(f"  [WEEKLY] Generated synthesis: {title}")

    return filename


def _format_highlights(highlights):
    """Format field highlights into markdown."""
    if isinstance(highlights, dict):
        lines = []
        for field, text in highlights.items():
            lines.append(f"### {field}\n{text}\n")
        return "\n".join(lines)
    elif isinstance(highlights, str):
        return highlights
    elif isinstance(highlights, list):
        return "\n".join(f"- {h}" for h in highlights)
    return "No highlights available."
